### Getting to know basics in `yfinance`
 `yfinance` is a library which can be used to retrieve market-data from Yahoo Finance.

In [9]:
import yfinance as yf

In [10]:
# Apple Stock as example
apple_ticker = "AAPL"
apple_stock = yf.Ticker(apple_ticker)

In [11]:
apple_stock.info

{'address1': 'One Apple Park Way',
 'city': 'Cupertino',
 'state': 'CA',
 'zip': '95014',
 'country': 'United States',
 'phone': '(408) 996-1010',
 'website': 'https://www.apple.com',
 'industry': 'Consumer Electronics',
 'industryKey': 'consumer-electronics',
 'industryDisp': 'Consumer Electronics',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': 'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide. The company offers iPhone, a line of smartphones; Mac, a line of personal computers; iPad, a line of multi-purpose tablets; and wearables, home, and accessories comprising AirPods, Apple Vision Pro, Apple TV, Apple Watch, Beats products, and HomePod, as well as Apple branded and third-party accessories. It also provides AppleCare support and cloud services; and operates various platforms, including the App Store that allow customers to discover and download applications and digital content, such as books, music, video, games, and podcasts, as well as advertising services include third-party licensing arrangements and its own advertising platforms. In addition, the company offers various subscription-based services, such as Apple Arcade, a game subscription service; Apple Fitness+, a personalized fitness service; Apple Music, which offers users a curated listening experience with on-demand radio stations; Apple News+, a subscription news and magazine service; Apple TV, which offers exclusive original content and live sports; Apple Card, a co-branded credit card; and Apple Pay, a cashless payment service, as well as licenses its intellectual property. The company serves consumers, and small and mid-sized businesses; and the education, enterprise, and government markets. It distributes third-party applications for its products through the App Store. The company also sells its products through its retail and online stores, and direct sales force; and third-party cellular network carriers and resellers. The company was formerly known as Apple Computer, Inc. and changed its name to Apple Inc. in January 2007. Apple Inc. was founded in 1976 and is headquartered in Cupertino, California.',
 'fullTimeEmployees': 150000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Timothy D. Cook',
   'age': 64,
   'title': 'CEO & Director',
   'yearBorn': 1961,
   'fiscalYear': 2025,
   'totalPay': 16759518,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Kevan  Parekh',
   'age': 53,
   'title': 'Senior VP & CFO',
   'yearBorn': 1972,
   'fiscalYear': 2025,
   'totalPay': 4034174,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Sabih  Khan',
   'age': 58,
   'title': 'Senior VP & Chief Operating Officer',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 5021905,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Katherine L. Adams',
   'age': 61,
   'title': 'Senior VP, General Counsel & Secretary',
   'yearBorn': 1964,
   'fiscalYear': 2025,
   'totalPay': 5022482,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': "Ms. Deirdre  O'Brien",
   'age': 58,
   'title': 'Senior Vice President of Retail & People',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 5037867,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Ben  Borders',
   'age': 44,
   'title': 'Principal Accounting Officer',
   'yearBorn': 1981,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Suhasini  Chandramouli',
   'title': 'Director of Investor Relations',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Kristin Huguet Quayle',
   'title': 'Vice President of Worldwide Communications',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Greg  Joswiak',
   'title': 'Senior Vice President of Worldwide Marketing',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Adrian  Perica',
   'age': 51,
   'title': 'Vice President of Corporate Development',
   'yearBorn': 1974,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 2,
 'boardRisk': 1,
 'compensationRisk': 7,
 'shareHolderRightsRisk': 1,
 'overallRisk': 1,
 'governanceEpochDate': 1772323200,
 'compensationAsOfEpochDate': 1767139200,
 'irWebsite': 'http://investor.apple.com/',
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 264.18,
 'open': 262.44,
 'dayLow': 260.2,
 'dayHigh': 266.53,
 'regularMarketPreviousClose': 264.18,
 'regularMarketOpen': 262.44,
 'regularMarketDayLow': 260.2,
 'regularMarketDayHigh': 266.53,
 'dividendRate': 1.04,
 'dividendYield': 0.39,
 'exDividendDate': 1770595200,
 'payoutRatio': 0.1304,
 'fiveYearAvgDividendYield': 0.52,
 'beta': 1.116,
 'trailingPE': 33.55133,
 'forwardPE': 28.450964,
 'volume': 41576035,
 'regularMarketVolume': 41576035,
 'averageVolume': 48329683,
 'averageVolume10days': 43011700,
 'averageDailyVolume10Day': 43011700,
 'bid': 264.45,
 'ask': 265.05,
 'bidSize': 1,
 'askSize': 2,
 'marketCap': 3890834833408,
 'nonDilutedMarketCap': 3886391380800,
 'fiftyTwoWeekLow': 169.21,
 'fiftyTwoWeekHigh': 288.62,
 'allTimeHigh': 288.62,
 'allTimeLow': 0.049107,
 'priceToSalesTrailing12Months': 8.931779,
 'fiftyDayAverage': 265.1808,
 'twoHundredDayAverage': 243.17525,
 'trailingAnnualDividendRate': 1.03,
 'trailingAnnualDividendYield': 0.003898857,
 'currency': 'USD',
 'tradeable': False,
 'enterpriseValue': 3909993365504,
 'profitMargins': 0.27037,
 'floatShares': 14656182062,
 'sharesOutstanding': 14681140000,
 'sharesShort': 133373267,
 'sharesShortPriorMonth': 113576032,
 'sharesShortPreviousMonthDate': 1768435200,
 'dateShortInterest': 1770940800,
 'sharesPercentSharesOut': 0.0091,
 'heldPercentInsiders': 0.0184,
 'heldPercentInstitutions': 0.65181,
 'shortRatio': 2.32,
 'shortPercentOfFloat': 0.0091,
 'impliedSharesOutstanding': 14697926000,
 'bookValue': 5.998,
 'priceToBook': 44.134712,
 'lastFiscalYearEnd': 1758931200,
 'nextFiscalYearEnd': 1790467200,
 'mostRecentQuarter': 1766793600,
 'earningsQuarterlyGrowth': 0.159,
 'netIncomeToCommon': 117776998400,
 'trailingEps': 7.89,
 'forwardEps': 9.30443,
 'lastSplitFactor': '4:1',
 'lastSplitDate': 1598832000,
 'enterpriseToRevenue': 8.976,
 'enterpriseToEbitda': 25.572,
 '52WeekChange': 0.122027755,
 'SandP52WeekChange': 0.19097292,
 'lastDividendValue': 0.26,
 'lastDividendDate': 1770595200,
 'quoteType': 'EQUITY',
 'currentPrice': 264.72,
 'targetHighPrice': 350.0,
 'targetLowPrice': 205.0,
 'targetMeanPrice': 293.06952,
 'targetMedianPrice': 300.0,
 'recommendationMean': 1.93617,
 'recommendationKey': 'buy',
 'numberOfAnalystOpinions': 41,
 'totalCash': 66907000832,
 'totalCashPerShare': 4.557,
 'ebitda': 152901992448,
 'totalDebt': 90509000704,
 'quickRatio': 0.845,
 'currentRatio': 0.974,
 'totalRevenue': 435617005568,
 'debtToEquity': 102.63,
 'revenuePerShare': 29.305,
 'returnOnAssets': 0.24377,
 'returnOnEquity': 1.5202099,
 'grossProfits': 206157004800,
 'freeCashflow': 106312753152,
 'operatingCashflow': 135471996928,
 'earningsGrowth': 0.183,
 'revenueGrowth': 0.157,
 'grossMargins': 0.47325,
 'ebitdaMargins': 0.35099998,
 'operatingMargins': 0.35374,
 'financialCurrency': 'USD',
 'symbol': 'AAPL',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Nasdaq Real Time Price',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 345479400000,
 'preMarketChange': -1.2399902,
 'preMarketChangePercent': -0.46841577,
 'preMarketPrice': 263.48,
 'regularMarketChange': 0.540009,
 'regularMarketDayRange': '260.2 - 266.53',
 'fullExchangeName': 'NasdaqGS',
 'averageDailyVolume3Month': 48329683,
 'fiftyTwoWeekLowChange': 95.509995,
 'fiftyTwoWeekLowChangePercent': 0.5644465,
 'fiftyTwoWeekRange': '169.21 - 288.62',
 'fiftyTwoWeekHighChange': -23.899994,
 'fiftyTwoWeekHighChangePercent': -0.082807824,
 'fiftyTwoWeekChangePercent': 12.202776,
 'dividendDate': 1770854400,
 'earningsTimestamp': 1769720400,
 'earningsTimestampStart': 1777582800,
 'earningsTimestampEnd': 1777582800,
 'earningsCallTimestampStart': 1769724000,
 'earningsCallTimestampEnd': 1769724000,
 'isEarningsDateEstimate': False,
 'epsTrailingTwelveMonths': 7.89,
 'epsForward': 9.30443,
 'epsCurrentYear': 8.5019,
 'priceEpsCurrentYear': 31.13657,
 'fiftyDayAverageChange': -0.4607849,
 'fiftyDayAverageChangePercent': -0.0017376256,
 'twoHundredDayAverageChange': 21.544754,
 'twoHundredDayAverageChangePercent': 0.08859765,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'averageAnalystRating': '1.9 - Buy',
 'cryptoTradeable': False,
 'shortName': 'Apple Inc.',
 'longName': 'Apple Inc.',
 'exchange': 'NMS',
 'messageBoardId': 'finmb_24937',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EST',
 'gmtOffSetMilliseconds': -18000000,
 'market': 'us_market',
 'esgPopulated': False,
 'marketState': 'PRE',
 'corporateActions': [],
 'preMarketTime': 1772542990,
 'regularMarketTime': 1772485202,
 'regularMarketChangePercent': 0.204409,
 'regularMarketPrice': 264.72,
 'displayName': 'Apple',
 'trailingPegRatio': 2.3708}

In [12]:
apple_stock.history(period="max")

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
1980-12-12 00:00:00-05:00,0.098298,0.098725,0.098298,0.098298,469033600,0.0,0.0
1980-12-15 00:00:00-05:00,0.093597,0.093597,0.093169,0.093169,175884800,0.0,0.0
1980-12-16 00:00:00-05:00,0.086758,0.086758,0.086331,0.086331,105728000,0.0,0.0
1980-12-17 00:00:00-05:00,0.088468,0.088895,0.088468,0.088468,86441600,0.0,0.0
1980-12-18 00:00:00-05:00,0.091032,0.091460,0.091032,0.091032,73449600,0.0,0.0
...,...,...,...,...,...,...,...
2026-02-24 00:00:00-05:00,267.859985,274.890015,267.709991,272.140015,47014600,0.0,0.0
2026-02-25 00:00:00-05:00,271.779999,274.940002,271.049988,274.230011,33714300,0.0,0.0
2026-02-26 00:00:00-05:00,274.950012,276.109985,270.799988,272.950012,32345100,0.0,0.0
2026-02-27 00:00:00-05:00,272.809998,272.809998,262.890015,264.179993,72366500,0.0,0.0
2026-03-02 00:00:00-05:00,262.410004,266.529999,260.200012,264.720001,41780100,0.0,0.0

In [15]:
apple_stock.splits

Date
1987-06-16 00:00:00-04:00    2.0
2000-06-21 00:00:00-04:00    2.0
2005-02-28 00:00:00-05:00    2.0
2014-06-09 00:00:00-04:00    7.0
2020-08-31 00:00:00-04:00    4.0
Name: Stock Splits, dtype: float64

In [17]:
apple_stock.institutional_holders

,Date Reported,Holder,pctHeld,Shares,Value,pctChange
0,2025-12-31,Vanguard Group Inc,0.0972,1426283914,377565879455,0.0192
1,2025-12-31,Blackrock Inc.,0.0786,1154665731,305663113719,0.0073
2,2025-12-31,State Street Corporation,0.0411,604056505,159905838740,0.0110
3,2025-12-31,"Geode Capital Management, LLC",0.0244,358032517,94778368337,0.0052
4,2025-12-31,"FMR, LLC",0.0209,307397264,81374204101,0.0137
5,2025-12-31,Morgan Stanley,0.0157,230483035,61013469306,0.0060
6,2025-12-31,"Berkshire Hathaway, Inc",0.0155,227917808,60334402411,-0.0432
7,2025-12-31,JPMORGAN CHASE & CO,0.0154,225419111,59672947339,-0.5237
8,2025-12-31,Price (T.Rowe) Associates Inc,0.0139,203499482,53870383123,-0.0435
9,2025-12-31,NORGES BANK,0.0131,192255086,50893766600,0.0129

In [26]:
apple_stock.recommendations

  period  strongBuy  buy  hold  sell  strongSell
0     0m          5   24    16     1           1
1    -1m          5   24    16     1           1
2    -2m          6   23    15     1           2
3    -3m          5   24    15     1           3

In [ ]:
apple_stock.financials

,2025-09-30,2024-09-30,2023-09-30,2022-09-30,2021-09-30
Tax Effect Of Unusual Items,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN
Tax Rate For Calcs,1.560000e-01,2.410000e-01,1.470000e-01,1.620000e-01,NaN
Normalized EBITDA,1.447480e+11,1.346610e+11,1.258200e+11,1.305410e+11,NaN
Net Income From Continuing Operation Net Minority Interest,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
Reconciled Depreciation,1.169800e+10,1.144500e+10,1.151900e+10,1.110400e+10,NaN
Reconciled Cost Of Revenue,2.209600e+11,2.103520e+11,2.141370e+11,2.235460e+11,NaN
EBITDA,1.447480e+11,1.346610e+11,1.258200e+11,1.305410e+11,NaN
EBIT,1.330500e+11,1.232160e+11,1.143010e+11,1.194370e+11,NaN
Net Interest Income,NaN,NaN,-1.830000e+08,-1.060000e+08,1.980000e+08
Interest Expense,NaN,NaN,3.933000e+09,2.931000e+09,2.645000e+09
Interest Income,NaN,NaN,3.750000e+09,2.825000e+09,2.843000e+09
Normalized Income,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
Net Income From Continuing And Discontinued Operation,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
Total Expenses,2.831110e+11,2.678190e+11,2.689840e+11,2.748910e+11,NaN
Total Operating Income As Reported,1.330500e+11,1.232160e+11,1.143010e+11,1.194370e+11,NaN
Diluted Average Shares,1.500470e+10,1.540810e+10,1.581255e+10,1.632582e+10,NaN
Basic Average Shares,1.494850e+10,1.534378e+10,1.574423e+10,1.621596e+10,NaN
Diluted EPS,7.460000e+00,6.080000e+00,6.130000e+00,6.110000e+00,NaN
Basic EPS,7.490000e+00,6.110000e+00,6.160000e+00,6.150000e+00,NaN
Diluted NI Availto Com Stockholders,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
Net Income Common Stockholders,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
Net Income,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
Net Income Including Noncontrolling Interests,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
Net Income Continuous Operations,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
Tax Provision,2.071900e+10,2.974900e+10,1.674100e+10,1.930000e+10,NaN
Pretax Income,1.327290e+11,1.234850e+11,1.137360e+11,1.191030e+11,NaN
Other Income Expense,-3.210000e+08,2.690000e+08,-5.650000e+08,-3.340000e+08,NaN
Other Non Operating Income Expenses,-3.210000e+08,2.690000e+08,-5.650000e+08,-3.340000e+08,NaN
Net Non Operating Interest Income Expense,NaN,NaN,-1.830000e+08,-1.060000e+08,1.980000e+08
Interest Expense Non Operating,NaN,NaN,3.933000e+09,2.931000e+09,2.645000e+09
Interest Income Non Operating,NaN,NaN,3.750000e+09,2.825000e+09,2.843000e+09
Operating Income,1.330500e+11,1.232160e+11,1.143010e+11,1.194370e+11,NaN
Operating Expense,6.215100e+10,5.746700e+10,5.484700e+10,5.134500e+10,NaN
Research And Development,3.455000e+10,3.137000e+10,2.991500e+10,2.625100e+10,NaN
Selling General And Administration,2.760100e+10,2.609700e+10,2.493200e+10,2.509400e+10,NaN
Gross Profit,1.952010e+11,1.806830e+11,1.691480e+11,1.707820e+11,NaN
Cost Of Revenue,2.209600e+11,2.103520e+11,2.141370e+11,2.235460e+11,NaN
Total Revenue,4.161610e+11,3.910350e+11,3.832850e+11,3.943280e+11,NaN
Operating Revenue,4.161610e+11,3.910350e+11,3.832850e+11,3.943280e+11,NaN

In [ ]:
apple_stock.actions

                           Dividends  Stock Splits
Date
1987-05-11 00:00:00-04:00   0.000536           0.0
1987-06-16 00:00:00-04:00   0.000000           2.0
1987-08-10 00:00:00-04:00   0.000536           0.0
1987-11-17 00:00:00-05:00   0.000714           0.0
1988-02-12 00:00:00-05:00   0.000714           0.0
...                              ...           ...
2025-02-10 00:00:00-05:00   0.250000           0.0
2025-05-12 00:00:00-04:00   0.260000           0.0
2025-08-11 00:00:00-04:00   0.260000           0.0
2025-11-10 00:00:00-05:00   0.260000           0.0
2026-02-09 00:00:00-05:00   0.260000           0.0

[95 rows x 2 columns]

In [28]:
yf.download("aapl")

[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open    Volume
Ticker            AAPL        AAPL        AAPL        AAPL      AAPL
Date
2026-02-03  269.228088  271.625839  267.359811  268.948351  64394700
2026-02-04  276.231506  278.689229  272.035451  272.035451  90545700
2026-02-05  275.652069  279.238709  272.974582  277.869995  52977400
2026-02-06  277.859985  280.647386  276.671095  276.860920  50453400
2026-02-09  274.619995  278.200012  271.700012  277.910004  44623400
2026-02-10  273.679993  275.369995  272.940002  274.890015  34376900
2026-02-11  275.500000  280.179993  274.450012  274.700012  51931300
2026-02-12  261.730011  275.720001  260.179993  275.589996  81077200
2026-02-13  255.779999  262.230011  255.449997  262.010010  56290700
2026-02-17  263.880005  266.290009  255.539993  258.049988  58469100
2026-02-18  264.350006  266.820007  262.450012  263.600006  34203300
2026-02-19  260.579987  264.480011  260.049988  262.600006  30845300
2026-02-20  264.579987  264.750000  258.160004  258.970001  42070500
2026-02-23  266.179993  269.429993  263.380005  263.489990  37308200
2026-02-24  272.140015  274.890015  267.709991  267.859985  47014600
2026-02-25  274.230011  274.940002  271.049988  271.779999  33714300
2026-02-26  272.950012  276.109985  270.799988  274.950012  32345100
2026-02-27  264.179993  272.809998  262.890015  272.809998  72366500
2026-03-02  264.720001  266.529999  260.200012  262.410004  41780100